version: "3.7"
services:
  proxy:
    build: proxy
    volumes:
      - ./web/source:/var/www
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  web:
    build: web
    volumes:
      - ./web/source:/var/www
      - ./web/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db

  db:
    build: db
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  backup:
    build: backup
    env_file:
      - .env
    volumes:
      - restic_cache:/root/.cache/restic
      - /var/lib/docker/volumes:/data/volumes
    restart: always

  logger:
    build: logger
    volumes:
      - ./logger/vector.toml:/etc/vector/vector.toml:ro
      # named volume, this is used to persist vector data between restarts
      - vector_data:/var/lib/vector
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure

volumes:
  caddy_config:
  caddy_data:
  db_data:
  restic_cache:
  vector_data:
