version: "3.7"
services:
  caddy:
    image: caddy:2.1.1-alpine
    volumes:
      - websource:/var/www
      - caddyfile:/etc/caddy
      - caddydata:/data
      - caddyconfig:/config
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  web:
    build: web
    volumes:
      - websource:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

  # vector:
  #   image: timberio/vector:0.10.0-alpine
  #   volumes:
  #     - vectorconfig:/etc/vector
  #     - vectordata:/var/lib/vector
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: on-failure

  fail2ban:
    image: crazymax/fail2ban:0.11.1
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - fail2bandata:/data
      - /var/log:/var/log:ro
    env_file:
      - ./fail2ban/.env
    restart: always

volumes:
  dbdata:
  websource:
  caddyfile:
  caddydata:
  caddyconfig:
  phpconf:
  # vectorconfig:
  # vectordata:
  fail2bandata:
