version: "3.7"
services:
  filebeat:
    container_name: filebeat
    build:
      context: filebeat
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # named volume, this is used to persist the registry file between restarts, so to avoid data duplication
      - filebeat_data:/usr/share/filebeat/data
      # needed to access all docker logs (read only)
      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
      # needed to access additional informations about containers
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

volumes:
  # create a persistent volume for Filebeat
  filebeat_data:
